### ISSUE TITLE
Doesn't use svo's queuing system.

### ISSUE THREAD

**Issue by slester** [AchaeaBashingScript/Bashing#32]
Perhaps it's misconfigured, but in both auto and svo set as the system, I can't do things like "dofree," which makes it difficult to do things like pick up gold, put up a defence, etc without having to stop and restart.

This also means that lots of things are buggy, like svo's balanceless vault detection.

**Comment by keneanung** [comment]
The basher uses svo.addbalanceful().

The issue is that expandAlias execution is delayed for batching and everything that is added to dofree/do/dor is ran through expandAlias... :rocket:

So this is actually a a svof bug.

**Comment by keneanung** [comment]
I created a new svof issue (svof/svof#79)

**Comment by keneanung** [comment]
Closing this, because svof bug as mentioned above.
