### ISSUE TITLE
Queueing configuration

### ISSUE THREAD

**Issue by jgh713** [AchaeaBashingScript/Bashing#38]
Allow users to toggle use of QUEUEing for their attacks. When dropping below the flee threshold, CQ eqbal and queue fleeing. Can't think of -too- many potential issues? Just an idea.

**Comment by keneanung** [comment]
That would be the case if you used anything else but svof... And I know of some people using the queueing setting of `none` instead of svof for hunting.

**Comment by jgh713** [comment]
Orly? Well damn. Guess I'll do that, then :)

**Comment by keneanung** [comment]
Under certain circumstances (like being monk relying on transmute), usinging server side queueing may be contra productive, so it's "not officially supported", so your request may have it's merit

**Comment by jgh713** [comment]
So, relevant issue, your system queues the first attack when hitting f2, but then just sits there uselessly. Doesn't even flee (this is using system none with svo installed). No visible errors. Even losing and regaining balance doesn't make the system attack again, nor does it flee when you lose enough health.
So, relevant issue, your system queues the first attack when hitting f2, but then just sits there uselessly. Doesn't even flee (this is using system none with svo installed). No visible errors. Even losing and regaining balance doesn't make the system attack again, nor does it flee when you lose enough health.

**Comment by keneanung** [comment]
Is ShowQueueAlerts turned on? The in game setting that says 'running queued
command'?

jgh713 <notifications@github.com> schrieb am Sa., 2. Juli 2016, 07:16:

**Comment by jgh713** [comment]
You're a peach.
