### ISSUE TITLE
Recent target prioritization

### ISSUE THREAD

**Issue by jgh713** [AchaeaBashingScript/Bashing#42]
For when you have to hit and run, it would be nice if the system remembered your most recent targets (last 1, 3, 10?) and prioritized those when you re-entered a room, to prevent soaking damage from something that's sitting at 2% the whole bloody time you're killing something else.

**Comment by keneanung** [comment]
That's something hidden somewhere in my personal WIP, but it still has a bug or two. Maybe I'll get around rounding this up soon-ish.

**Comment by keneanung** [comment]
Actually, it's already in the pre-release since https://github.com/AchaeaBashingScript/Bashing/commit/d6eff602dd380adfe2a0f3dbda7d6e6ca365590b (would be pre-release https://github.com/AchaeaBashingScript/Bashing/releases/tag/v1.8-pre-31ff9f9-master)
