### ISSUE TITLE
Targeting items in hand now

### ISSUE THREAD

**Issue by slester** [AchaeaBashingScript/Bashing#43]
I just installed the latest stable and the lastest dev scripts, and both of them are trying to target corpses in my hand instead of enemies that are alive. :(

I changed my attack to `echo &tar` and got the following:

```
ih
golem247772         a creaking rust golem
keneanung: Nothing will stand in our way.
260259
You are holding:
Corpses:
   mastiff260259       the corpse of a howling blood mastiff
```

**Comment by keneanung** [comment]
I can't reproduce that, but that doesn't mean much.

Can you enable debug mode with `lua keneanung.bashing.toggleDebug()`, then enter a room with a target and try to attack, then paste the output somewhere? Be careful, that mode is spammy. You can disable it again with the same command.
