### ISSUE TITLE
Depthswalker Compatibility

### ISSUE THREAD

**Issue by alex-d-schroder** [AchaeaBashingScript/Bashing#46]
The list of battlerages for Depthswalker is out of order, compared to other classes. The big damage ability, Lash, is gained as the second ability, throwing the rest of the list out of wack. The script will try to use the aeon affliction ability instead of the shieldbreaker when it needs to break shields, and will use shieldbreaker when trying to do the heavy damage ability. Unless the admin change the ordering to better fit other classes, a special case might need to be made for Depthswalker classes.

**Comment by keneanung** [comment]
Fixed by #49
