### ISSUE TITLE
Not clear system setup

### ISSUE THREAD

**Issue by gilmoa** [AchaeaBashingScript/Bashing#56]
The [Quickstart](https://github.com/AchaeaBashingScript/Bashing#quickstart) section states 

> - If using a custom system: setup the system table and configure kconfig bashing system name

and [Support for other systems](https://github.com/AchaeaBashingScript/Bashing#support-for-other-systems)

> While two often used systems are supported by the bashing script

It might be worth stating those supported system with the relative `kconfig bashing system` since I've seen people assuming svo and wundersys are not custom systems.

**Comment by keneanung** [comment]
Would it help to name the systems explicitly?
> If not using svof, wundersys or stock server side queuing: setup the system table and configure kconfig bashing system name

For the second line, maybe something like the following may be clearer:
> While two often used systems (svof and wundersys) are supported out of the box by the bashing script

**Comment by gilmoa** [comment]
Yes, that's exactly what I was thinking. I think the system table from shipping for svof is `systems.svo` though?

**Comment by keneanung** [comment]
Have a look at #57, does this answer your questions?

**Comment by gilmoa** [comment]
It does! Thank you
