### ISSUE TITLE
Battlerage attacks not working

### ISSUE THREAD

**Issue by robaxelsen** [AchaeaBashingScript/Bashing#74]
Hi. Setting up on a new comp, and I am having issues with bashing script never firing any battlerage attack. Using vs 1.8. Using in-client svof. kconfig bashing set to auto. Fighting as dragon. Serverside on, ShowQueueAlerts NO. Usequeueing NO. Any ideas?

I keep getting this:
```
[ERROR:] object:<event handler function> function:<keneanung.bashing.vitalsChangeRecord>
        <...ob/.config/mudlet/profiles/Achaea/Bashing/script.lua:1663: attempt to index field '?' 
(a nil value)>
```

Same when I try with druid.

**Comment by keneanung** [comment]
Try using the 1.9 prerelease at https://github.com/AchaeaBashingScript/Bashing/releases/tag/v1.9-pre-2f4ca7d-master since 1.8 doesn't contain the move of battlerage to the new skillset yet.

**Comment by robaxelsen** [comment]
> Try using the 1.9 prerelease at https://github.com/AchaeaBashingScript/Bashing/releases/tag/v1.9-pre-2f4ca7d-master since 1.8 doesn't contain the move of battlerage to the new skillset yet.

Works, thanks! Made the mistake of clicking on "Release: 1.8" in the sidebar, not realizing that there were more releases available.
