### ISSUE TITLE
Latest Pre-release (1.9-pre-efa8559-master) cannot be installed.

### ISSUE THREAD

**Issue by Sharidin** [AchaeaBashingScript/Bashing#87]
Hello! The change in [this commit](https://github.com/AchaeaBashingScript/Bashing/pull/86/commits/b556300ddc17d9a276951be62198cea50912c81e#diff-15ff2f2beced641e04e229db10025557f089eb59caa9ff8b0e437c314fb2f2a8R419-R425) is creating an issue for people trying to install the script, at least on a fresh profile.

If installed through the package manager, `getModulePath("Bashing")` returns `nil` so the package is broken and nothing happens.

If installed through the module manager, `getModulePath("Bashing")` returns something like `C:/Users/Username/ModuleDownloadOrInstallLocation/Bashing.mpackage`. Also, the `string.gsub()` method is trying to replace something that would never appear there (`Bashing.xml`). The `scriptFile` variable ends up being something like `C:/Users/Username/ModuleDownloadOrInstallLocation/Bashing.mpackagescript.lua`.

Given also the `echo()` after it, this does look like a possible debug change (if just the `Bashing.xml` was installed through module manager) that found its way onto the final version?

**Comment by keneanung** [comment]
Thanks for the report and detailed analysis! :star: Please have a look at https://github.com/AchaeaBashingScript/Bashing/releases/tag/1.9-pre-04b3227-master, which should fix this issue.

**Comment by Sharidin** [comment]
Works great now, thanks!
